[workspace]
members = ["host", "guest", "macros", "examples/*"]

[workspace.package]
version = "0.1.0"

[workspace.dependencies]
bincode = "2.0.0-rc.2"
parking_lot = "0.12"
wasmer = "3"

macros = { path = "macros" }

[profile.release]
lto = true
