[package]
name = "scotch-host"
edition = "2021"
version.workspace = true
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/scotch"

[dependencies]
scotch-host-macros.workspace = true
parking_lot.workspace = true
bincode.workspace = true
wasmer.workspace = true
