[package]
name = "scotch-host-macros"
edition = "2021"
description = "Scotch host macros."
version.workspace = true
license = "MIT"
authors = ["ItsEthra"]
repository = "https://github.com/ItsEthra/scotch"

[lib]
proc-macro = true

[dependencies]
syn.workspace = true
quote = "1"
